include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - _to_delete/**
    - _stage/**
    - build/**
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    # Manter o build limpo, mas nao bloquear em estilo.
    todo: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_single_quotes
    - sort_child_properties_last
    - unnecessary_this
